.PHONY: test test-suite build build-webrtc check-webrtc vendor check

# Suppress Deno's background update check for all invocations.
export DENO_NO_UPDATE_CHECK := 1

# Resolve the project's pinned Deno binary deterministically.
# Evaluates the webrun launcher up to the "end preamble" sentinel (no side
# effects) to compute the exact version+SHA path.
DENO_BIN := $(shell bash -c 'eval "$$(sed -n "1,/^. --- end preamble ---/p" src/webrun.preamble.sh)"; echo "$$DENO_BIN"')

# Checksum: prefer sha256sum (Linux), fall back to shasum -a 256 (macOS)
SHA256SUM := $(shell command -v sha256sum 2>/dev/null || echo "shasum -a 256")

# Bootstrap the Deno binary if it hasn't been downloaded yet.
$(DENO_BIN):
	@bash src/webrun.preamble.sh --version > /dev/null

# Install npm dependencies (werift) into the webrtc build directory.
WEBRTC_BUILD := src/internal/webrtc
WEBRTC_BUNDLE := src/deno/extensions/webrtc/bundle.js

$(WEBRTC_BUILD)/node_modules: $(WEBRTC_BUILD)/deno.json $(DENO_BIN)
	cd $(WEBRTC_BUILD) && $(abspath $(DENO_BIN)) install
	@touch $(WEBRTC_BUILD)/node_modules

# Which webrun binary the test suite exercises. Exported so Deno sees it.
export WEBRUN_BIN ?= $(CURDIR)/webrun

TEST_ARG ?=

# All .test.ts files, partitioned by runner:
# - WORKER_TESTS: run inside the webrun harness (src/worker/*)
# - NATIVE_TESTS: run via deno test, auto-registered through codegen (everything else)
NATIVE_SRCS := $(shell find src -name "*.ts" -not -path "*/deno/worker/*" -not -name "*.test.ts" -not -name "*.denotest.ts" -not -name "build.ts" -not -path "*/node_modules/*")
NATIVE_TESTS := $(shell find src -name "*.test.ts" -not -path "*/deno/worker/*" -not -path "*/node_modules/*")

WORKER_SRCS := $(shell find src/deno/worker -name "*.ts" -not -name "build.ts" -not -path "*/node_modules/*")
WORKER_TESTS := $(shell find src/deno/worker -name "*.test.ts" -not -path "*/node_modules/*")

DENOTESTS := $(shell find src test integration -name "*.denotest.ts" -not -name "*.generated.denotest.ts" -not -path "*/node_modules/*" 2>/dev/null)
NATIVE_DENOTEST := src/test/native.generated.denotest.ts

# Generate a .denotest.ts that imports NATIVE_TESTS for native deno test execution.
# These tests use Deno-specific APIs (FFI, dlopen, etc.) that aren't available in the worker host.
$(NATIVE_DENOTEST): $(NATIVE_TESTS)
	@echo '// AUTO-GENERATED — do not edit. Regenerated by make.' > $@
	@echo 'import { registerTests } from "../deno/test/deno.ts";' >> $@
	@for f in $(NATIVE_TESTS); do \
		varname=$$(echo "$$f" | sed 's|[/.]|_|g'); \
		relpath=$$(python3 -c "import os; print(os.path.relpath('$$f', 'src/test'))"); \
		echo "import * as $$varname from \"./$$relpath\";" >> $@; \
	done
	@for f in $(NATIVE_TESTS); do \
		varname=$$(echo "$$f" | sed 's|[/.]|_|g'); \
		echo "registerTests(\"$$varname\", $$varname);" >> $@; \
	done

# All non-test sources that esbuild may transitively bundle.
ALL_SRCS := $(shell find src -name "*.ts" -not -name "*.test.ts" -not -name "*.denotest.ts" -not -name "build.ts" -not -path "*/node_modules/*")
BUNDLE_SRCS := $(shell find bundle -name "*.ts" -not -path "*/node_modules/*")

# Build the bundled webrun executable.
build: $(DENO_BIN) $(ALL_SRCS) $(BUNDLE_SRCS)
	$(DENO_BIN) run -A --no-check --config deno.json bundle/webrun.ts > webrun.tmp && mv webrun.tmp webrun && chmod +x webrun

test-suite: $(DENO_BIN) $(NATIVE_DENOTEST)
	$(WEBRUN_BIN) --test=$(TEST_ARG) $(WORKER_TESTS)
	@echo "=== Native ==="
	$(DENO_BIN) test -A --no-check --config deno.json $(NATIVE_DENOTEST) $(DENOTESTS)
	$(WEBRUN_BIN) --test=$(TEST_ARG) integration/suite_worker.test.ts

# Run all tests against the built executable.
test: build check-webrtc
	$(MAKE) test-suite

# Regenerate webrtc bundle.js and verify it matches what's committed.
check-webrtc: $(WEBRTC_BUILD)/node_modules $(DENO_BIN)
	@echo "Checking webrtc bundle reproducibility..."
	@HASH_BEFORE=$$($(SHA256SUM) $(WEBRTC_BUNDLE) | cut -d' ' -f1) && \
	 cp $(WEBRTC_BUNDLE) $(WEBRTC_BUNDLE).bak && \
	 $(DENO_BIN) run -A --no-check bundle/webrtc.ts > $(WEBRTC_BUNDLE) && \
	 HASH_AFTER=$$($(SHA256SUM) $(WEBRTC_BUNDLE) | cut -d' ' -f1) && \
	 mv $(WEBRTC_BUNDLE).bak $(WEBRTC_BUNDLE) && \
	 if [ "$$HASH_BEFORE" != "$$HASH_AFTER" ]; then \
	   echo "FAIL: webrtc bundle is not reproducible." >&2; \
	   echo "  committed: $$HASH_BEFORE" >&2; \
	   echo "  generated: $$HASH_AFTER" >&2; \
	   echo "  Run 'make build-webrtc' to update." >&2; \
	   exit 1; \
	 fi
	@echo "webrtc bundle: OK (reproducible)"

# Rebuild the webrtc bundle (updates the committed artifact).
# Runs in a fixed-point loop to prove the output is deterministic.
build-webrtc: $(WEBRTC_BUILD)/node_modules $(DENO_BIN)
	@for i in 1 2 3 4 5; do \
	  $(DENO_BIN) run -A --no-check bundle/webrtc.ts > $(WEBRTC_BUNDLE).tmp; \
	  if cmp -s $(WEBRTC_BUNDLE) $(WEBRTC_BUNDLE).tmp 2>/dev/null; then \
	    rm $(WEBRTC_BUNDLE).tmp; \
	    echo "webrtc bundle: fixed point reached (pass $$i)"; \
	    break; \
	  fi; \
	  mv $(WEBRTC_BUNDLE).tmp $(WEBRTC_BUNDLE); \
	done

# Vendor all JSR/external dependencies into vendor/.
vendor: $(DENO_BIN)
	$(DENO_BIN) cache --vendor webrun.ts src/deno/host/host.ts src/deno/worker/worker.ts

# Type-check all source files.
check: $(DENO_BIN)
	$(DENO_BIN) check --config deno.json $(NATIVE_SRCS) $(WORKER_SRCS)
	$(DENO_BIN) check --config deno.json $(NATIVE_TESTS) $(WORKER_TESTS)
