/**
 * Deno FFI adapter for macOS Seatbelt (sandbox_init_with_parameters).
 *
 * Applies seatbelt profiles generated by the pure policy translator
 * to the current process via libSystem.B.dylib FFI.
 *
 * All Deno FFI types are injected via makeSeatbelt() — this module
 * contains no ambient Deno global access.
 */

// ── Structural dependency types ─────────────────────────────────────────────

/** Opaque pointer value used by FFI */
export type PointerValue = Deno.PointerValue;

/** The subset of UnsafePointer this adapter actually calls. */
interface UnsafePointerAPI {
    of(buf: Uint8Array<ArrayBuffer>): PointerValue;
    create(value: bigint): PointerValue;
}

/** A view into native memory for reading C strings from error buffers. */
interface UnsafePointerViewConstructor {
    new (ptr: Deno.PointerObject): { getCString(): string };
}

/** Spec for a single foreign function symbol. */
interface ForeignFunctionSpec {
    parameters: readonly Deno.NativeType[];
    result: Deno.NativeResultType;
}

/** The Deno APIs that seatbelt actually needs. */
export interface SeatbeltDeps {
    dlopen<S extends Record<string, ForeignFunctionSpec>>(
        path: string,
        symbols: S,
    ): Deno.DynamicLibrary<S>;
    UnsafePointer: UnsafePointerAPI;
    UnsafePointerView: UnsafePointerViewConstructor;
}

// ── Internal types ──────────────────────────────────────────────────────────

interface LibSandbox {
    sandbox_init_with_parameters(
        profile: PointerValue,
        flags: bigint,
        params: PointerValue,
        errorbuf: PointerValue,
    ): number;
    sandbox_free_error(errorbuf: PointerValue): void;
}

/** sandbox_init_with_parameters flag: profile is a raw inline SBPL string. */
const SANDBOX_INLINE_PROFILE = 0n;

// ── Factory ─────────────────────────────────────────────────────────────────

export interface Seatbelt {
    /**
     * Probes the macOS sandbox subsystem for availability.
     *
     * Checks that libSystem.B.dylib can be loaded and the
     * sandbox_init_with_parameters symbol is present. Does NOT call
     * sandbox_init — that would irreversibly sandbox the current process.
     */
    querySeatbeltSupport(): boolean;

    /**
     * Applies a Seatbelt (macOS sandbox) profile to the current process.
     *
     * This is irreversible — once applied, restrictions cannot be loosened,
     * only narrowed by subsequent calls. Restrictions are inherited by all
     * child processes.
     */
    applySeatbelt(sbplProfile: string): void;
}

export function makeSeatbelt(deps: SeatbeltDeps): Seatbelt {
    let _lib: LibSandbox | null = null;

    function getLibSandbox(): LibSandbox {
        if (_lib) return _lib;

        const lib = deps.dlopen("libSystem.B.dylib", {
            sandbox_init_with_parameters: {
                parameters: ["pointer", "u64", "pointer", "pointer"] as const,
                result: "i32",
            },
            sandbox_free_error: {
                parameters: ["pointer"] as const,
                result: "void",
            },
        });

        _lib = {
            sandbox_init_with_parameters: (profile, flags, params, errorbuf) =>
                lib.symbols.sandbox_init_with_parameters(profile, flags, params, errorbuf) as number,
            sandbox_free_error: (errorbuf) =>
                lib.symbols.sandbox_free_error(errorbuf),
        };

        return _lib;
    }

    function querySeatbeltSupport(): boolean {
        getLibSandbox();
        return true;
    }

    function applySeatbelt(sbplProfile: string): void {
        const lib = getLibSandbox();

        const profile = new TextEncoder().encode(sbplProfile + "\0");
        const profileBuf = new Uint8Array(profile.buffer) as Uint8Array<ArrayBuffer>;
        const profilePtr = deps.UnsafePointer.of(profileBuf);

        // errorbuf: pointer to a char* — 8 bytes for a 64-bit pointer.
        const errorbufStorage = new BigUint64Array(1);
        const errorbufPtr = deps.UnsafePointer.of(
            new Uint8Array(errorbufStorage.buffer) as Uint8Array<ArrayBuffer>
        );

        const result = lib.sandbox_init_with_parameters(
            profilePtr,
            SANDBOX_INLINE_PROFILE,
            null, // no parameters — profile values are fully inlined
            errorbufPtr,
        );

        if (result !== 0) {
            const errPtr = deps.UnsafePointer.create(errorbufStorage[0]);
            let msg = "(unknown error)";
            if (errPtr) {
                msg = new deps.UnsafePointerView(errPtr).getCString();
                lib.sandbox_free_error(errPtr);
            }
            throw new Error(`[webrun] Fatal: sandbox_init_with_parameters failed: ${msg}`);
        }
    }

    return { querySeatbeltSupport, applySeatbelt };
}
